### ISSUE TITLE
sakugabooru under heavy load?

### ISSUE THREAD

**Issue by 152334H** [zhenglinpan/SakugaDataset#2]
the site at which all videos are hosted, www.sakugabooru.com, appears to be extremely slow and unresponsive:
```bash
$ python3 download.py
Downloading sakugadataset_train_full.parquet -->
Total videos to download: 142089
Downloading:   0%|                                                                           | 0/142089 [00:00<?, ?it/s]
```
Despite having executed for over 18 minutes, I have yet to finish downloading even 1 video:
```bash
$ ps 31062
    PID TTY      STAT   TIME COMMAND
  31062 pts/4    Sl+    0:18 python3 download.py
```
You can see [this asciinema recording](https://asciinema.org/a/p7YYyzkYDAMbiQ79wDajdkIbr) to understand just how slow the download is; it is barely 1KB/s.

![https://asciinema.org/a/p7YYyzkYDAMbiQ79wDajdkIbr](https://asciinema.org/a/p7YYyzkYDAMbiQ79wDajdkIbr.svg)

Note that my home network is not slow:
```bash
$ speedtest-cli
Retrieving speedtest.net configuration...
Testing from MyRepublic (hidden)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Sandya Networks (Jakarta Selatan) [909.48 km]: 20.776 ms
Testing download speed................................................................................
Download: 61.64 Mbit/s
Testing upload speed......................................................................................................
Upload: 153.84 Mbit/s
```

---

is it possible to rehost the data elsewhere? I can provide a free R2 bucket.

**Comment by zhenglinpan** [comment]
Hi 152334H,

Thanks for keeping me posted.

I guess you're right. I just tested the pipeline, the same thing happened to me.

I've taken steps to manage the load for now. Researchers need to fill out a form to download the dataset. I hope this will work. Please wait a few days until it's working again.

Sorry for the inconvenience. Didn't see that coming, everyone is enthusiastic about cartoons.

**Comment by zhenglinpan** [comment]
Hi 152334H,

Thanks for keeping me posted.

I guess you're right. I just tested the pipeline, the same thing happened to me.

I hope my work do not burden their server much. I've taken steps to manage the load for now, researchers need to fill out a form to download the dataset, so there will be much less downloaders. I hope this will work. Please wait a few days until it's available again.

Sorry for the inconvenience.

**Comment by 152334H** [comment]
I don't think the volume of people downloading from their site is an issue; to be frank I would be surprised if more than 5 people had tried the SakugaDataset download process yet. Most likely sakugabooru or their host or their network provider or etc. have implemented heavy network throttling, or are under an unrelated attack.

**Comment by zhenglinpan** [comment]
Yeah, you're not wrong. This has never happened before when I was downloading the data prior to making the project public. Even though I do not know the precise number of downloaders, all I can do is to prevent such things from happening. We should not crack their server.

**Comment by 152334H** [comment]
I think they changed their cloudflare settings to I'm Under Attack mode. All requests get hit by their captcha, now.

**Comment by zhenglinpan** [comment]
Thanks for your quick feedback. I believe you're right—they recently added Cloudflare protections and probably have IUAM turned on. I tried to find a workaround, but there doesn't seem to be an easy way. All the videos are still accessible in a browser but not from our crawler... I'll keep looking for solutions, but for now I have to leave it to the downloaders and provide the Parquet files...
