### ISSUE TITLE
Host the dataset on the Hugging Face Hub

### ISSUE THREAD

**Issue by davanstrien** [zhenglinpan/SakugaDataset#5]
Very cool dataset! I think it would be nice for the community if the dataset were hosted on the Hugging Face Hub rather than needing to send a request via Google form. The Hub has a gating feature (https://huggingface.co/docs/hub/datasets-gated) so it would be possible to host it there but still be able to control access. Happy to help with this if it's of interest :)

**Comment by zhenglinpan** [comment]
Thanks davanstrien! Yeah I was gonna do that, thanks for your nice suggestion!

**Comment by yumlevi** [comment]
@zhenglinpan your work seems fantastic, let us know where we can expect to see it on huggingface

**Comment by zhenglinpan** [comment]
Hey guys. I have created the datasets at [huggingface](https://huggingface.co/datasets/aidenpan/Sakuga-42M).

**Comment by somepago** [comment]
Not able to apply for access on HF. :( 

Throws this error, but i agreed to
![Screenshot 2024-05-20 at 4 26 12 PM](https://github.com/zhenglinpan/SakugaDataset/assets/14878056/2203ab48-0e43-4b5b-9b0a-96e27c5160ae)
 that item.

**Comment by zhenglinpan** [comment]
Hi @somepago thank you for letting me know that. This seems an known issue from huggingface as described in [this link](https://discuss.huggingface.co/t/400-error-metadata-is-required-on-all-spaces-ive-created-in-the-past/72355). I did some modifications, it worked for me now, would you please try again?
