### ISSUE TITLE
Question: How did you get video clips?

### ISSUE THREAD

**Issue by vbkaisetsu** [zhenglinpan/SakugaDataset#6]
README says

> copyrights of images and videos in the dataset are owned by their respective creators, we will remove the works from the dataset upon request to protect the author's right

Were they lawfully obtained?
Could you clarify the origin of each video clip?

**Comment by zhenglinpan** [comment]
For those who are not familiar with how modern large-scale datasets work: 

As any other academic researchs, like [LAION-5B](https://laion.ai/blog/laion-5b/), [InternVid](https://github.com/OpenGVLab/InternVideo/tree/main/Data/InternVid), [Panda-70M](https://snap-research.github.io/Panda-70M/), [VideoProM](https://huggingface.co/datasets/WenhaoWang/VidProM) and many others, our dataset DOES NOT contain any images or videos in our dataset. We do not hold any images or videos.

**Comment by vbkaisetsu** [comment]
> our dataset DOES NOT contain any images or videos in our dataset.

I do not understand what you meant. Could you explain the details?

> we will remove the works from the dataset upon request to protect the author's right

If the dataset does not contain any images or videos, what do you remove from the dataset?

**Comment by vbkaisetsu** [comment]
> The Sakuga-42M dataset comprises cartoon videos collected from the Internet. We
employ crawlers to aggregate publicly available cartoon content from streaming platforms such as
YouTube and Twitter, as well as animation communities, while adhering to their privacy regulations.
This effort culminates in a dataset over 150k raw cartoon videos, predominantly in mkv, mp4, and
webm formats. In order to ensure uniformity and maintain a superior standard of quality, we opt out
of gif and other less prevalent formats, which collectively constitute less than 1% of the collected
data.

I might have understood.
This dataset is based on YouTube and you hold just links to each video clip. Right?

**Comment by yumlevi** [comment]
> > our dataset DOES NOT contain any images or videos in our dataset.
> 
> I do not understand what you meant. Could you explain the details?
> 
> > we will remove the works from the dataset upon request to protect the author's right
> 
> If the dataset does not contain any images or videos, what do you remove from the dataset?

He means this dataset contains only links to the videos and data he himself created such as captions, cut timings, scores for dynamic movement etc, the videos themselves are hosted on the site with the same name, if you want to know the source of the videos that question would be better directed to the people who made the videos.

**Comment by Tomboyrespect** [comment]
> > > our dataset DOES NOT contain any images or videos in our dataset.
> > 
> > 
> > I do not understand what you meant. Could you explain the details?
> > > we will remove the works from the dataset upon request to protect the author's right
> > 
> > 
> > If the dataset does not contain any images or videos, what do you remove from the dataset?
> 
> He means this dataset contains only links to the videos and data he himself created such as captions, cut timings, scores for dynamic movement etc, the videos themselves are hosted on the site with the same name, if you want to know the source of the videos that question would be better directed to the people who made the videos.

Except it very obviously doesn't contain a single piece of original work or permission to use any of the clips he's using to train the AI.
